// SPDX-License-Identifier: MIT
//

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let leaves_dir = Path::new(&manifest_dir).join("src/leaves");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let mut modules = fs::read_dir(&leaves_dir)
        .expect("read src/leaves")
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().into_string().ok()?;
            name.strip_suffix(".rs")
                .and_then(|stem| stem.starts_with("leaf_").then(|| stem.to_owned()))
        })
        .collect::<Vec<_>>();

    modules.sort();

    let mut code = String::from("// @generated by build.rs — do not edit\n\n");
    for module in &modules {
        let file_path = leaves_dir.join(format!("{module}.rs"));
        code.push_str(&format!(
            "#[path = r\"{}\"]\nmod {module};\npub use {module}::*;\n\n",
            file_path.display()
        ));
        println!("cargo:rerun-if-changed=src/leaves/{module}.rs");
    }

    fs::write(Path::new(&out_dir).join("leaves_registry.rs"), code)
        .expect("write leaves_registry.rs");

    println!("cargo:rerun-if-changed=src/leaves");
    println!("cargo:rerun-if-changed=build.rs");
}
